**HEALTH RISK CLASSIFICATION**
(Arham Abdullah
24F-AI-017)

In [3]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "diabetes.csv"

# Load the latest version
df = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "jamaltariqcheema/pima-indians-diabetes-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documentation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:")
display(df.head())

Using Colab cache for faster access to the 'pima-indians-diabetes-dataset' dataset.
First 5 records:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1

In [5]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [7]:
x = df.drop('Outcome' , axis=1)
y = df['Outcome']

In [9]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y, test_size=0.2 ,random_state=42)

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
xtrainScaled = scaler.fit_transform(xtrain)
xtestScaled = scaler.transform(xtest)

In [18]:
from sklearn.svm import SVC
svm = SVC(kernel='linear', random_state=42)
svm.fit(xtrainScaled,ytrain)

SVC(kernel='linear', random_state=42)

In [19]:
svmTrainPred = svm.predict(xtrainScaled)
svmTestPred =  svm.predict(xtestScaled)

In [20]:
from sklearn.metrics import accuracy_score
svmTrainAcc = accuracy_score(ytrain,svmTrainPred)
svmTestAcc = accuracy_score(ytest,svmTestPred)

In [21]:
svmTrainAcc

0.7736156351791531

In [22]:
svmTestAcc

0.7922077922077922

In [23]:
from sklearn.tree import DecisionTreeClassifier
tree =  DecisionTreeClassifier(random_state=42)
tree.fit(xtrainScaled,ytrain)

DecisionTreeClassifier(random_state=42)

In [24]:
treeTrainPred = tree.predict(xtrainScaled)
treeTestPred =  tree.predict(xtestScaled)

In [25]:
treeTrainAcc = accuracy_score(ytrain,treeTrainPred)
treeTestAcc = accuracy_score(ytest,treeTestPred)

In [26]:
treeTrainAcc

1.0

In [27]:
treeTestAcc

0.8441558441558441